//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmaPay.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UmaPay.Resource.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave API es bligatoria..
        /// </summary>
        public static string ApplicationApiKeyRequired {
            get {
                return ResourceManager.GetString("ApplicationApiKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La pasareala de pagos no está asociada con esta aplicación.
        /// </summary>
        public static string ApplicationGetwayInvalid {
            get {
                return ResourceManager.GetString("ApplicationGetwayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta aplicación no está activa..
        /// </summary>
        public static string ApplicationInactive {
            get {
                return ResourceManager.GetString("ApplicationInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La aplicación es inválida..
        /// </summary>
        public static string ApplicationInvalid {
            get {
                return ResourceManager.GetString("ApplicationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la aplicacion ya se encuentra registrado.
        /// </summary>
        public static string ApplicationNameExists {
            get {
                return ResourceManager.GetString("ApplicationNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la aplicación debe tener entre 3 y 100 caracteres..
        /// </summary>
        public static string ApplicationNameLenght {
            get {
                return ResourceManager.GetString("ApplicationNameLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la aplicación no puede estar vacío..
        /// </summary>
        public static string ApplicationNameRequired {
            get {
                return ResourceManager.GetString("ApplicationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación no encontrada..
        /// </summary>
        public static string ApplicationNotFound {
            get {
                return ResourceManager.GetString("ApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticación fallida para ApiKey: {0}. Error: {1}.
        /// </summary>
        public static string AuthController_AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthController_AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado del modelo inválido para intento de inicio de sesión con ApiKey: {0}.
        /// </summary>
        public static string AuthController_InvalidModelState {
            get {
                return ResourceManager.GetString("AuthController_InvalidModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de inicio de sesión completado a las {0} para ApiKey: {1}. Duración: {2}. Éxito: {3}.
        /// </summary>
        public static string AuthController_LoginAttemptCompleted {
            get {
                return ResourceManager.GetString("AuthController_LoginAttemptCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de inicio de sesión comenzado a las {0} para ApiKey: {1}.
        /// </summary>
        public static string AuthController_LoginAttemptStarted {
            get {
                return ResourceManager.GetString("AuthController_LoginAttemptStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creación de transacción fallida para ApiKey: {0}. Error: {1}.
        /// </summary>
        public static string AuthController_TransactionCreationFailed {
            get {
                return ResourceManager.GetString("AuthController_TransactionCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado durante el inicio de sesión para ApiKey: {0}.
        /// </summary>
        public static string AuthController_UnexpectedError {
            get {
                return ResourceManager.GetString("AuthController_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado.
        /// </summary>
        public static string AuthController_UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("AuthController_UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro ha sido creado con exito.
        /// </summary>
        public static string Controller_CreateSucess {
            get {
                return ResourceManager.GetString("Controller_CreateSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro ha sido actualizado con exito.
        /// </summary>
        public static string Controller_UpdateSucess {
            get {
                return ResourceManager.GetString("Controller_UpdateSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El destino es inválido..
        /// </summary>
        public static string CountryInvalid {
            get {
                return ResourceManager.GetString("CountryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El país no existe.
        /// </summary>
        public static string CountryNameInvalid {
            get {
                return ResourceManager.GetString("CountryNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código sap es obligatorio.
        /// </summary>
        public static string CustomerCodeSapRequired {
            get {
                return ResourceManager.GetString("CustomerCodeSapRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear el cliente.
        /// </summary>
        public static string CustomerCreationError {
            get {
                return ResourceManager.GetString("CustomerCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo del ciente es obligatorio.
        /// </summary>
        public static string CustomerEmailRequired {
            get {
                return ResourceManager.GetString("CustomerEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es obligatorio.
        /// </summary>
        public static string CustomerFirstNameRequired {
            get {
                return ResourceManager.GetString("CustomerFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apellido es obligatorio.
        /// </summary>
        public static string CustomerLastNameRequired {
            get {
                return ResourceManager.GetString("CustomerLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ciente es obligatorio.
        /// </summary>
        public static string CustomerRequired {
            get {
                return ResourceManager.GetString("CustomerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El argumento &apos;{0}&apos; no puede ser nulo..
        /// </summary>
        public static string Error_ArgumentStatusNull {
            get {
                return ResourceManager.GetString("Error_ArgumentStatusNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado de la factura es obligatorio..
        /// </summary>
        public static string Error_InvoiceStatusRequired {
            get {
                return ResourceManager.GetString("Error_InvoiceStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la factura de la transacción..
        /// </summary>
        public static string Error_TransactionInvoiceNotFound {
            get {
                return ResourceManager.GetString("Error_TransactionInvoiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al procesar evento de Wompi para la transacción con referencia .
        /// </summary>
        public static string ErrorAtProcessWompiEvent {
            get {
                return ResourceManager.GetString("ErrorAtProcessWompiEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de aplicación recuperado: {0}.
        /// </summary>
        public static string GatewayController_ApplicationCodeRetrieved {
            get {
                return ResourceManager.GetString("GatewayController_ApplicationCodeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron gateways para la aplicación con código: {0}.
        /// </summary>
        public static string GatewayController_GatewaysNotFound {
            get {
                return ResourceManager.GetString("GatewayController_GatewaysNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateways recuperados con éxito para la aplicación con código: {0}. Cantidad de gateways: {1}.
        /// </summary>
        public static string GatewayController_GatewaysRetrieved {
            get {
                return ResourceManager.GetString("GatewayController_GatewaysRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de obtención de gateways completado a las {0}. Duración: {1}. Éxito: {2}.
        /// </summary>
        public static string GatewayController_GetAttemptCompleted {
            get {
                return ResourceManager.GetString("GatewayController_GetAttemptCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de obtención de gateways iniciado a las {0}.
        /// </summary>
        public static string GatewayController_GetAttemptStarted {
            get {
                return ResourceManager.GetString("GatewayController_GetAttemptStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso no autorizado. No se pudo obtener el código de aplicación.
        /// </summary>
        public static string GatewayController_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("GatewayController_UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado durante la obtención de gateways.
        /// </summary>
        public static string GatewayController_UnexpectedError {
            get {
                return ResourceManager.GetString("GatewayController_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La configuración ya se encuentra registrada.
        /// </summary>
        public static string GatewayExists {
            get {
                return ResourceManager.GetString("GatewayExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La psarela de pagos es invalida..
        /// </summary>
        public static string GatewayInvalid {
            get {
                return ResourceManager.GetString("GatewayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasarela de pagos no encontrada..
        /// </summary>
        public static string GatewayNotFound {
            get {
                return ResourceManager.GetString("GatewayNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL portal de pagos es obligatorio..
        /// </summary>
        public static string GatewayRequired {
            get {
                return ResourceManager.GetString("GatewayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales no válidas..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El stoken es inválido.
        /// </summary>
        public static string InvalidStoken {
            get {
                return ResourceManager.GetString("InvalidStoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información de la pasarela en inválida..
        /// </summary>
        public static string JWTGatewayRequired {
            get {
                return ResourceManager.GetString("JWTGatewayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT Secret no está configurado..
        /// </summary>
        public static string JWTSecretRequired {
            get {
                return ResourceManager.GetString("JWTSecretRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json inválidos para la la actualización del pago.
        /// </summary>
        public static string NuveiController_InvalidJson {
            get {
                return ResourceManager.GetString("NuveiController_InvalidJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos inválidos para la la actualización del pago {0}.
        /// </summary>
        public static string NuveiController_InvalidModelState {
            get {
                return ResourceManager.GetString("NuveiController_InvalidModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información actualizada con éxito..
        /// </summary>
        public static string NuveiController_Sucess {
            get {
                return ResourceManager.GetString("NuveiController_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor del pago debe ser mayor a 0..
        /// </summary>
        public static string PaymentAmountInvalid {
            get {
                return ResourceManager.GetString("PaymentAmountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ntento de generación de enlace de pago completado a las {0} para el código de pasarela: {1}. Duración: {2}. Éxito: {3}.
        /// </summary>
        public static string PaymentController_GenerateLinkAttemptCompleted {
            get {
                return ResourceManager.GetString("PaymentController_GenerateLinkAttemptCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de generación de enlace de pago iniciado a las {0} para el código de pasarela: {1}.
        /// </summary>
        public static string PaymentController_GenerateLinkAttemptStarted {
            get {
                return ResourceManager.GetString("PaymentController_GenerateLinkAttemptStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos inválidos para la generación de enlace de pago con código de pasarela: {0}.
        /// </summary>
        public static string PaymentController_InvalidModelState {
            get {
                return ResourceManager.GetString("PaymentController_InvalidModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallo en la generación del enlace de pago para el código de pasarela: {0}. Error: {1}.
        /// </summary>
        public static string PaymentController_LinkGenerationFailed {
            get {
                return ResourceManager.GetString("PaymentController_LinkGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlace de pago generado con éxito para el código de pasarela: {0}. ID de Transacción: {1}.
        /// </summary>
        public static string PaymentController_LinkGenerationSucceeded {
            get {
                return ResourceManager.GetString("PaymentController_LinkGenerationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso no autorizado. Aplicación: {0}, Transacción: {1}.
        /// </summary>
        public static string PaymentController_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("PaymentController_UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado durante la generación del enlace de pago para el código de pasarela: {0}.
        /// </summary>
        public static string PaymentController_UnexpectedError {
            get {
                return ResourceManager.GetString("PaymentController_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al generar el enlace de pago..
        /// </summary>
        public static string PaymentLinkError {
            get {
                return ResourceManager.GetString("PaymentLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación no fue exitosa:{0}.
        /// </summary>
        public static string PaymentLinkErrorStatus {
            get {
                return ResourceManager.GetString("PaymentLinkErrorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelado por proceso automatico..
        /// </summary>
        public static string TaskProcessInitiated {
            get {
                return ResourceManager.GetString("TaskProcessInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al ejecutar la transacción:.
        /// </summary>
        public static string TransactionError {
            get {
                return ResourceManager.GetString("TransactionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La transaccion ya fue registrada, debe validar el estado..
        /// </summary>
        public static string TransactionExists {
            get {
                return ResourceManager.GetString("TransactionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacción no encontrada.
        /// </summary>
        public static string TransactionNoFound {
            get {
                return ResourceManager.GetString("TransactionNoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la transacción con referencia: {0}.
        /// </summary>
        public static string TransactionReferenceRequired {
            get {
                return ResourceManager.GetString("TransactionReferenceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado {0}.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error desconocido. Nuestro equipo técnico ha sido notificado y estamos trabajando para resolverlo. Por favor, inténtelo de nuevo más tarde..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El evento de Wompi no pudo ser procesado..
        /// </summary>
        public static string UnprocessableWompiEvent {
            get {
                return ResourceManager.GetString("UnprocessableWompiEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento de wompi no procesable: .
        /// </summary>
        public static string UnProcessableWompiEvent_ {
            get {
                return ResourceManager.GetString("UnProcessableWompiEvent ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction.updated.
        /// </summary>
        public static string WompiTransactionUpdatedEvent {
            get {
                return ResourceManager.GetString("WompiTransactionUpdatedEvent", resourceCulture);
            }
        }
    }
}
